input_dir: data
imaris_xml: raw/012523_303_1_63X_stitchable.xml
output_dir: data

hne:
  hne_res_level: 0 # index for highest resolution level in Imaris data
  nuclear_channel: 3
  cyto_channel: 4
  fixed_z_position: 11
  z_anisotropy: 1.0

segmentation:
  out_dir: CellposeSegmentations
  cellpose_model: cyto
  cellpose_diameter: 30.0
  batch_size: 2
  anisotropy: 0.0
  use_gpu: false
  gpu_device: "0"

analysis:
  output_dir: analysis
  classes:
    - control
    - treated
  segmentation_path:
    - CellposeSegmentations
    - CellposeSegmentations
  raw_image_path:
    - raw
    - raw
  xml_files_path:
    - raw/012523_303_1_63X_stitchable.xml
    - raw/012523_303_1_63X_stitchable.xml
  gh2ax_threshold:
    - 1300
    - 1300
  cd8_threshold:
    - 750
    - 1000
  gh2ax_pixel_count_threshold: 100
  radii:
    - 32
    - 48
    - 64
    - 128
  n_pseudo_classes: 5
  cd8_dapi_box_overlap_threshold: 0.2

plot:
  plot_output_format: pdf
  classes:
    - control
    - treated
  num_pseudo_classes: 5

geometry:
  enabled: false
  run_labels2starconvex: true
  depends_on_segmentation: true
  input_dir: CellposeSegmentations
  output_dir: Cellpose3DGeometryAndFeatures
  tile_json: tileArrangement.json
  anisotropy: 0.0
  compute_haralick: false
  separate_feature_files: false
